locations:
  INBOX:
    position: [0.0, 0.0]
    side: right
    tag_2:
      offset: [-0.05, 0.06250, -0.009]
  STORE:
    position: [ -0.50, 0.0]
    side: right
    tag_1:
      offset: [-0.05, 0.06250, -0.009]
  LH1:
    position: [0.0, 0.81]
    side: left
    tag_3:
      offset: [-0.05, 0.06250, -0.009]
  LH2:
    position: [0.60, 0.81]
    side: left
    tag_0:
      offset: [-0.05, 0.06250, -0.009]
  current_location:
